### ISSUE TITLE
nlu.yml and domain.yml look like not working

### ISSUE THREAD

**Issue by youyi1314** [paulpierre/RasaGPT#69]
nlu.yml:
```
nlu:
- intent: greet
  examples: |
    - hey
    - hello
    - hi
    - hello there
    - good morning
    - good evening
    - moin
    - hey there
    - let's go
    - hey dude
    - goodmorning
    - goodevening
    - good afternoon
```

domain.yml
```
responses:
  utter_greet:
  - text: "Hi, what i can help you?"
```

i did `make rasa-train` and `make restart` but why when i send `hi`, it go to chatgpt api? and not direct reply `Hi, what i can help you?`?

<img width="1518" alt="Screenshot 2024-01-24 at 10 11 19 PM" src="https://github.com/paulpierre/RasaGPT/assets/8391468/9d3e59e7-0007-4760-badd-6fc52b5c7108">

**Comment by youyi1314** [comment]
Add code below to rules: solved the issue
```
- rule: greet
  steps:
  - intent: greet
  - action: utter_greet
```

**Comment by youyi1314** [comment]
Add code below to rules: solved the issue
```
- rule: greet
  steps:
  - intent: greet
  - action: utter_greet
```
